# This is a basic workflow to help you get started with Actions

name: Sample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Select an environment"
        required: false
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_dev:
    name: Deploy to dev
    if: ${{ github.event.inputs.environment == 'dev' }}
    runs-on: ubuntu-latest
    environment:
      name: dev  # Must match a pre-configured environment in your repo settings
    env:
      ENV_KEY: ${{ vars.ENV }}
      SECRET_API_KEY: ${{ secrets.API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Debug Variables
        run: |
            echo "TEST_VAR: ${{env.SECRET_API_KEY}}"
            if [ -z "${{env.SECRET_API_KEY}}" ]; then
            echo "TEST_VAR is empty or not being passed correctly."
            else
              echo "TEST_VAR value is: ${{env.SECRET_API_KEY}}"
            fi

      - name: Debug Variables 1
        run: |
            echo "TEST_VAR: ${{env.ENV_KEY}}"
            if [ -z "${{env.ENV_KEY}}" ]; then
            echo "TEST_VAR is empty or not being passed correctly."
            else
              echo "TEST_VAR value is: ${{env.ENV_KEY}}"
            fi
            
      - name: Print selected environment
        run: echo "Selected environment :- ${{ github.event.inputs.environment }}"
      
      - name: Deploy to dev
        if: ${{ github.event.inputs.environment == 'dev' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
      
      - name: environment Variables
        run: echo "environment Variables:- ${{env.ENV_KEY}}"

      - name: secrets Variables
        run: echo "secrets Variables:- ${{env.SECRET_API_KEY}}"
  
  deploy_qa:
    name: Deploy to qa
    if: ${{ github.event.inputs.environment == 'qa' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment }}  # Must match a pre-configured environment in your repo settings
    # needs: deploy_dev   # Optional dependency if you want production to wait
    env:
      ENV_KEY: ${{ vars.ENV }}
      SECRET_API_KEY: ${{ secrets.API_KEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Debug Variables
        run: |
            echo "TEST_VAR: ${{env.SECRET_API_KEY}}"
            if [ -z "${{env.SECRET_API_KEY}}" ]; then
            echo "TEST_VAR is empty or not being passed correctly."
            else
              echo "TEST_VAR value is: ${{env.SECRET_API_KEY}}"
            fi

      - name: Debug Variables 1
        run: |
            echo "TEST_VAR: ${{env.ENV_KEY}}"
            if [ -z "${{env.ENV_KEY}}" ]; then
            echo "TEST_VAR is empty or not being passed correctly."
            else
              echo "TEST_VAR value is: ${{env.ENV_KEY}}"
            fi
            
      - name: Print selected environment
        run: echo "Selected environment :- ${{ github.event.inputs.environment }}"
      

      - name: Deploy to qa
        if: ${{ github.event.inputs.environment == 'qa' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

      
      - name: environment Variables
        run: echo "environment Variables:- ${{env.ENV_KEY}}"

      - name: secrets Variables
        run: echo "secrets Variables:- ${{env.SECRET_API_KEY}}"
