# This is a basic workflow to help you get started with Actions

name: Sample

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      environment:
        description: "Select an environment"
        required: false
        default: "production"
        type: choice
        options:
          - production
          - staging
          - development

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ env.SAMPLE_ENV }}
      SECRET_API_KEY: ${{ secrets.SAMPLE_SECRETS }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Debug Variables
        run: |
            echo "TEST_VAR: $API_KEY"
            if [ -z "$API_KEY" ]; then
            echo "TEST_VAR is empty or not being passed correctly."
            else
              echo "TEST_VAR value is: $API_KEY"
            fi
            
      - name: Print selected environment
        run: echo "Selected environment :- ${{ github.event.inputs.environment }}"
      
      - name: Deploy to Production
        if: ${{ github.event.inputs.environment == 'production' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

      - name: Deploy to Staging
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"

      - name: Deploy to Development
        if: ${{ github.event.inputs.environment == 'development' }}
        run: echo "Deploying to ${{ github.event.inputs.environment }} environment"


      - name: Deploy 1 to ${{ github.event.inputs.environment }}
        if: ${{ github.event.inputs.environment == 'production' || github.event.inputs.environment == 'development' || github.event.inputs.environment == 'staging'}}
        run: echo "Deploying 1 to ${{ github.event.inputs.environment }} environment"
      
      - name: Access Environment Variable
        env:
          API_KEYs: ${{ env.SAMPLE_ENV }} # Access the environment variable
        run: echo "The API_KEY is $API_KEYs"

      - name: Access Secret
        env:
          SECRET_API_KEYs: ${{ secrets.SAMPLE_SECRETS }} # Access the secret
        run: echo "The secret API key :-  $SECRET_API_KEYs is hidden!"
        
      - name: environment Variables
        run: echo "environment Variables:- $API_KEY"

      - name: secrets Variables
        run: echo "secrets Variables:- $SECRET_API_KEY"


      - name: environment Variables 1
        run: echo "environment Variables:- $API_KEYs"

      - name: secrets Variables 1
        run: echo "secrets Variables:- $SECRET_API_KEYs"     
